version: '3.8'
 
services:
  database:
    image: 'postgres:13-alpine'
    restart: 'always'
    environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: '1234'
        POSTGRES_DB: 'musical_events'
    ports:
            - '5432:5432'
  crawler:
    build: .
    image: "mamdasan/crawler:latest"
    network_mode: 'host'

